<?php
namespace More_MCP\Capabilities;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Integrations {

	public static function all(): array {
		return array(
			\More_MCP\Integrations\WooCommerce::class,
			\More_MCP\Integrations\LiteSpeed::class,
			\More_MCP\Integrations\Elementor::class,
			\More_MCP\Integrations\Divi::class,
			\More_MCP\Integrations\BeaverBuilder::class,
			\More_MCP\Integrations\SiteOriginPanels::class,
			\More_MCP\Integrations\ACF::class,
			\More_MCP\Integrations\MetaBox::class,
			\More_MCP\Integrations\Redirection::class,
			\More_MCP\Integrations\Analytics::class,
			\More_MCP\Integrations\Email::class,
			\More_MCP\Integrations\Forms::class,
			\More_MCP\Integrations\WPRocket::class,
			\More_MCP\Integrations\W3TotalCache::class,
			\More_MCP\Integrations\RedisObjectCache::class,
			\More_MCP\Integrations\Autoptimize::class,
			\More_MCP\Integrations\WPOptimize::class,
			\More_MCP\Integrations\UpdraftPlus::class,
			\More_MCP\Integrations\BackWPup::class,
			\More_MCP\Integrations\Duplicator::class,
			\More_MCP\Integrations\WPvivid::class,
			\More_MCP\Integrations\Wordfence::class,
			\More_MCP\Integrations\Defender::class,
			\More_MCP\Integrations\SolidSecurity::class,
			\More_MCP\Integrations\Sucuri::class,
			\More_MCP\Integrations\ReallySimpleSecurity::class,
			\More_MCP\Integrations\Akismet::class,
			\More_MCP\Integrations\Imagify::class,
			\More_MCP\Integrations\EWWW::class,
			\More_MCP\Integrations\Smush::class,
			\More_MCP\Integrations\ShortPixel::class,
			\More_MCP\Integrations\InstantImages::class,
			\More_MCP\Integrations\EventsCalendar::class,
			\More_MCP\Integrations\SugarCalendar::class,
			\More_MCP\Integrations\EventsManager::class,
			\More_MCP\Integrations\TranslatePress::class,
			\More_MCP\Integrations\Polylang::class,
			\More_MCP\Integrations\WPML::class,
			\More_MCP\Integrations\Weglot::class,
			\More_MCP\Integrations\GeoDirectory::class,
			\More_MCP\Integrations\BusinessDirectory::class,
			\More_MCP\Integrations\IvorySearch::class,
			\More_MCP\Integrations\UncannyAutomator::class,
			\More_MCP\Integrations\Blog2Social::class,
			\More_MCP\Integrations\Estatik::class,
			\More_MCP\Integrations\ToolsetTypes::class,
			\More_MCP\Integrations\FluentCRM::class,
			\More_MCP\Integrations\MailPoet::class,
			\More_MCP\Integrations\Groundhogg::class,
			\More_MCP\Integrations\GiveWP::class,
			\More_MCP\Integrations\PaidMembershipsPro::class,
			\More_MCP\Integrations\SimpleMembership::class,
			\More_MCP\Integrations\ProfilePress::class,
			\More_MCP\Integrations\RestrictContent::class,
			\More_MCP\Integrations\Charitable::class,
			\More_MCP\Integrations\BBPress::class,
			\More_MCP\Integrations\BuddyPress::class,
			\More_MCP\Integrations\FluentSupport::class,
			\More_MCP\Integrations\LearnPress::class,
			\More_MCP\Integrations\Sensei::class,
			\More_MCP\Integrations\Masteriyo::class,
			\More_MCP\Integrations\Tutor::class,
			\More_MCP\Integrations\LifterLMS::class,
			\More_MCP\Integrations\Amelia::class,
			\More_MCP\Integrations\LatePoint::class,
			\More_MCP\Integrations\Bookly::class,
			\More_MCP\Integrations\BookingPress::class,
			\More_MCP\Integrations\Pods::class,
			\More_MCP\Integrations\CptUi::class,
			\More_MCP\Integrations\MbCpt::class,
			\More_MCP\Integrations\EDD::class,
			\More_MCP\Integrations\FluentCart::class,
			\More_MCP\Integrations\Ai1wm::class,
			\More_MCP\Integrations\Patchstack::class,
			\More_MCP\Integrations\Relevanssi::class,
			\More_MCP\Integrations\SliceWP::class,
			\More_MCP\Integrations\AutomatorWP::class,
			\More_MCP\Integrations\WPJobManager::class,
			\More_MCP\Integrations\WpGoMaps::class,

			
			\More_MCP\Integrations\AIMedia::class,
			\More_MCP\Integrations\Snippets::class,
		);
	}
}
