<?php
namespace More_MCP\MCP;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Action_Labels {

	public static function label( string $action ): string {
		$map = self::map();
		return $map[ $action ] ?? '';
	}

	public static function map(): array {
		return array(
			
			'oauth:authorize' => __( 'Client asked to connect (authorization page shown)', 'more-mcp' ),
			'oauth:token' => __( 'Connection completed (tokens issued)', 'more-mcp' ),
			'oauth:register' => __( 'Client registered itself', 'more-mcp' ),
			'oauth:metadata' => __( 'Client read connection details', 'more-mcp' ),
			'oauth:protected_resource' => __( 'Client read connection details', 'more-mcp' ),
			'oauth:unknown' => __( 'OAuth request', 'more-mcp' ),

			
			'oauth:reset' => __( 'You reset OAuth state (all clients must reconnect)', 'more-mcp' ),
			'oauth:revoke_all_sessions' => __( 'You revoked all sessions', 'more-mcp' ),
			'oauth:revoke_grant' => __( 'You disconnected a client', 'more-mcp' ),
			'oauth:delete_session' => __( 'You ended a session', 'more-mcp' ),
			'oauth:clear_all_sessions' => __( 'You ended all sessions', 'more-mcp' ),
			'oauth:clear_field' => __( 'You cleared an OAuth field', 'more-mcp' ),
			'session:delete' => __( 'You ended a session', 'more-mcp' ),
			'session:delete_all' => __( 'You ended all sessions', 'more-mcp' ),
			'integration:toggle' => __( 'You toggled an integration', 'more-mcp' ),
			'option_source:toggle' => __( 'You toggled a settings source', 'more-mcp' ),
			'ability_namespace:toggle' => __( 'You toggled an ability group', 'more-mcp' ),
			'scope:set' => __( 'You changed an access scope', 'more-mcp' ),
			'custom_options:set' => __( 'You edited the option allowlist', 'more-mcp' ),
			'ttl:set' => __( 'You changed session length', 'more-mcp' ),
			'undo:run' => __( 'You undid an operation', 'more-mcp' ),
			
			'tools/call:wp_get_posts' => __( 'Read posts', 'more-mcp' ),
			'tools/call:wp_get_post' => __( 'Read a post', 'more-mcp' ),
			'tools/call:wp_create_post' => __( 'Created a post', 'more-mcp' ),
			'tools/call:wp_update_post' => __( 'Updated a post', 'more-mcp' ),
			'tools/call:wp_delete_post' => __( 'Deleted a post', 'more-mcp' ),
			'tools/call:wp_replace_in_post' => __( 'Edited text inside a post', 'more-mcp' ),
			'tools/call:wp_count_posts' => __( 'Counted posts', 'more-mcp' ),
			'tools/call:wp_get_post_types' => __( 'Listed post types', 'more-mcp' ),
			'tools/call:wp_get_page' => __( 'Read a page', 'more-mcp' ),
			'tools/call:wp_get_pages' => __( 'Read pages', 'more-mcp' ),
			'tools/call:wp_create_page' => __( 'Created a page', 'more-mcp' ),
			'tools/call:wp_update_page' => __( 'Updated a page', 'more-mcp' ),
			'tools/call:wp_delete_page' => __( 'Deleted a page', 'more-mcp' ),
			'tools/call:wp_replace_in_page' => __( 'Edited text inside a page', 'more-mcp' ),
			'tools/call:wp_get_post_revisions' => __( 'Read revision history', 'more-mcp' ),
			'tools/call:wp_restore_revision' => __( 'Restored a revision', 'more-mcp' ),
			'tools/call:wp_search' => __( 'Searched content', 'more-mcp' ),
			
			'tools/call:wp_get_media' => __( 'Browsed the media library', 'more-mcp' ),
			'tools/call:wp_get_media_item' => __( 'Read a media item', 'more-mcp' ),
			'tools/call:wp_upload_media' => __( 'Uploaded media', 'more-mcp' ),
			'tools/call:wp_upload_media_from_url' => __( 'Uploaded media from a URL', 'more-mcp' ),
			'tools/call:wp_update_media' => __( 'Updated media details', 'more-mcp' ),
			'tools/call:wp_delete_media' => __( 'Deleted media', 'more-mcp' ),
			'tools/call:wp_set_featured_image' => __( 'Changed a featured image', 'more-mcp' ),
			'tools/call:wp_process_image' => __( 'Resized or converted an image', 'more-mcp' ),
			'tools/call:wp_count_media' => __( 'Counted media items', 'more-mcp' ),
			
			'tools/call:wp_get_comments' => __( 'Read comments', 'more-mcp' ),
			'tools/call:wp_get_pending_comments' => __( 'Read comments awaiting moderation', 'more-mcp' ),
			'tools/call:wp_create_comment' => __( 'Posted a comment', 'more-mcp' ),
			'tools/call:wp_approve_comment' => __( 'Approved a comment', 'more-mcp' ),
			'tools/call:wp_spam_comment' => __( 'Marked a comment as spam', 'more-mcp' ),
			'tools/call:wp_trash_comment' => __( 'Trashed a comment', 'more-mcp' ),
			'tools/call:wp_delete_comment' => __( 'Deleted a comment', 'more-mcp' ),
			
			'tools/call:wp_get_users' => __( 'Listed users', 'more-mcp' ),
			'tools/call:wp_get_user' => __( 'Read a user profile', 'more-mcp' ),
			
			'tools/call:wp_get_taxonomies' => __( 'Listed taxonomies', 'more-mcp' ),
			'tools/call:wp_get_categories' => __( 'Listed categories', 'more-mcp' ),
			'tools/call:wp_get_tags' => __( 'Listed tags', 'more-mcp' ),
			'tools/call:wp_get_terms' => __( 'Listed terms', 'more-mcp' ),
			'tools/call:wp_create_term' => __( 'Created a term', 'more-mcp' ),
			'tools/call:wp_update_term' => __( 'Renamed a term', 'more-mcp' ),
			'tools/call:wp_delete_term' => __( 'Deleted a term', 'more-mcp' ),
			'tools/call:wp_add_post_terms' => __( 'Tagged a post', 'more-mcp' ),
			'tools/call:wp_count_terms' => __( 'Counted terms', 'more-mcp' ),
			'tools/call:wp_get_term_meta' => __( 'Read term metadata', 'more-mcp' ),
			'tools/call:wp_update_term_meta' => __( 'Updated term metadata', 'more-mcp' ),
			'tools/call:wp_delete_term_meta' => __( 'Deleted term metadata', 'more-mcp' ),
			
			'tools/call:wp_get_post_meta' => __( 'Read custom fields', 'more-mcp' ),
			'tools/call:wp_add_post_meta' => __( 'Added a custom field', 'more-mcp' ),
			'tools/call:wp_update_post_meta' => __( 'Updated a custom field', 'more-mcp' ),
			'tools/call:wp_delete_post_meta' => __( 'Deleted a custom field', 'more-mcp' ),
			'tools/call:wp_get_option' => __( 'Read a setting', 'more-mcp' ),
			'tools/call:wp_update_option' => __( 'Changed a setting', 'more-mcp' ),
			
			'tools/call:wp_get_menus' => __( 'Listed menus', 'more-mcp' ),
			'tools/call:wp_create_menu' => __( 'Created a menu', 'more-mcp' ),
			'tools/call:wp_get_menu_items' => __( 'Read menu items', 'more-mcp' ),
			'tools/call:wp_create_menu_item' => __( 'Added a menu item', 'more-mcp' ),
			'tools/call:wp_update_menu_item' => __( 'Updated a menu item', 'more-mcp' ),
			'tools/call:wp_delete_menu_item' => __( 'Deleted a menu item', 'more-mcp' ),
			'tools/call:wp_reorder_menu_items' => __( 'Reordered menu items', 'more-mcp' ),
			
			'tools/call:wp_get_site_info' => __( 'Read site info', 'more-mcp' ),
			'tools/call:wp_get_site_status' => __( 'Read site health', 'more-mcp' ),
			'tools/call:wp_get_error_log_tail' => __( 'Read the error log', 'more-mcp' ),
			'tools/call:wp_get_cron_schedule' => __( 'Read the cron schedule', 'more-mcp' ),
			'tools/call:wp_get_active_theme' => __( 'Read the active theme', 'more-mcp' ),
			'tools/call:wp_get_themes' => __( 'Listed themes', 'more-mcp' ),
			'tools/call:wp_get_themes_status' => __( 'Checked theme updates', 'more-mcp' ),
			'tools/call:wp_get_plugins' => __( 'Listed plugins', 'more-mcp' ),
			'tools/call:wp_get_plugin_updates' => __( 'Checked plugin updates', 'more-mcp' ),
			'tools/call:wp_get_plugin_settings' => __( 'Read plugin settings', 'more-mcp' ),
			'tools/call:wp_get_theme_mods' => __( 'Read theme settings', 'more-mcp' ),
			'tools/call:wp_update_theme_mod' => __( 'Changed a theme setting', 'more-mcp' ),
			'tools/call:wp_get_custom_css' => __( 'Read custom CSS', 'more-mcp' ),
			'tools/call:wp_update_custom_css' => __( 'Changed custom CSS', 'more-mcp' ),
			'tools/call:wp_get_sidebars' => __( 'Listed widget areas', 'more-mcp' ),
			'tools/call:wp_get_widgets' => __( 'Listed widgets', 'more-mcp' ),
			'tools/call:wp_update_widget' => __( 'Changed a widget', 'more-mcp' ),
			'tools/call:wp_get_permalink_structure' => __( 'Read permalink settings', 'more-mcp' ),
			'tools/call:wp_update_permalink_structure' => __( 'Changed permalink settings', 'more-mcp' ),
			'tools/call:wp_set_front_page' => __( 'Changed the front page', 'more-mcp' ),
			'tools/call:wp_list_page_templates' => __( 'Listed page templates', 'more-mcp' ),
			'tools/call:wp_set_page_template' => __( 'Changed the page template', 'more-mcp' ),
			
			'tools/call:wp_get_seo_meta' => __( 'Read SEO metadata', 'more-mcp' ),
			'tools/call:wp_update_seo_meta' => __( 'Changed SEO metadata', 'more-mcp' ),
			'tools/call:wp_get_term_seo_meta' => __( 'Read term SEO metadata', 'more-mcp' ),
			'tools/call:wp_update_term_seo_meta' => __( 'Changed term SEO metadata', 'more-mcp' ),
			'tools/call:seo_audit_meta_tags' => __( 'Audited rendered SEO tags', 'more-mcp' ),
			
			'tools/call:blocks_get_post_tree' => __( 'Read the block layout', 'more-mcp' ),
			'tools/call:blocks_get_block' => __( 'Read a block', 'more-mcp' ),
			'tools/call:blocks_list_types' => __( 'Listed block types', 'more-mcp' ),
			'tools/call:blocks_get_type_schema' => __( 'Read a block schema', 'more-mcp' ),
			'tools/call:blocks_insert' => __( 'Added a block', 'more-mcp' ),
			'tools/call:blocks_update' => __( 'Edited a block', 'more-mcp' ),
			'tools/call:blocks_delete' => __( 'Deleted a block', 'more-mcp' ),
			'tools/call:blocks_move' => __( 'Moved a block', 'more-mcp' ),
			'tools/call:blocks_validate_markup' => __( 'Checked block markup', 'more-mcp' ),
			'tools/call:blocks_get_template' => __( 'Read a template', 'more-mcp' ),
			'tools/call:blocks_update_template' => __( 'Updated a template', 'more-mcp' ),
			'tools/call:blocks_revert_template' => __( 'Reverted a template', 'more-mcp' ),
			'tools/call:blocks_list_templates' => __( 'Listed templates', 'more-mcp' ),
			'tools/call:blocks_list_patterns' => __( 'Listed block patterns', 'more-mcp' ),
			'tools/call:blocks_get_reusable' => __( 'Read a reusable block', 'more-mcp' ),
			'tools/call:blocks_list_reusable' => __( 'Listed reusable blocks', 'more-mcp' ),
			'tools/call:blocks_create_reusable' => __( 'Created a reusable block', 'more-mcp' ),
			'tools/call:blocks_update_reusable' => __( 'Updated a reusable block', 'more-mcp' ),
			'tools/call:blocks_delete_reusable' => __( 'Deleted a reusable block', 'more-mcp' ),
			'tools/call:blocks_get_global_styles' => __( 'Read global styles', 'more-mcp' ),
			'tools/call:blocks_update_global_styles' => __( 'Updated global styles', 'more-mcp' ),
			
			'tools/call:wp_install_plugin' => __( 'Installed a plugin', 'more-mcp' ),
			'tools/call:wp_update_plugin' => __( 'Updated a plugin', 'more-mcp' ),
			'tools/call:wp_activate_plugin' => __( 'Activated a plugin', 'more-mcp' ),
			'tools/call:wp_deactivate_plugin' => __( 'Deactivated a plugin', 'more-mcp' ),
			'tools/call:wp_delete_plugin' => __( 'Deleted a plugin', 'more-mcp' ),
			'tools/call:wp_update_theme' => __( 'Updated a theme', 'more-mcp' ),
			'tools/call:wp_activate_theme' => __( 'Switched the theme', 'more-mcp' ),
			'tools/call:wp_delete_theme' => __( 'Deleted a theme', 'more-mcp' ),
			
			'tools/call:webhook_list' => __( 'Listed webhooks', 'more-mcp' ),
			'tools/call:webhook_create' => __( 'Created a webhook', 'more-mcp' ),
			'tools/call:webhook_delete' => __( 'Deleted a webhook', 'more-mcp' ),
			
			'tools/call:more_mcp_connection_health' => __( 'Checked connection health', 'more-mcp' ),
			'tools/call:more_mcp_undo_last_operation' => __( 'Undid an operation', 'more-mcp' ),
			
			'tools/call:ahrefs_domain_rating' => __( 'Checked Ahrefs Domain Rating', 'more-mcp' ),
			'tools/call:semrush_domain_overview' => __( 'Checked Semrush domain overview', 'more-mcp' ),
			'tools/call:semrush_organic_keywords' => __( 'Read Semrush organic keywords', 'more-mcp' ),
			'tools/call:semrush_keyword_overview' => __( 'Read Semrush keyword data', 'more-mcp' ),
			'tools/call:semrush_keyword_difficulty' => __( 'Read Semrush keyword difficulty', 'more-mcp' ),
			'tools/call:semrush_related_keywords' => __( 'Read Semrush related keywords', 'more-mcp' ),
			'tools/call:semrush_question_keywords' => __( 'Read Semrush question keywords', 'more-mcp' ),
			'tools/call:semrush_competitors' => __( 'Read Semrush competitors', 'more-mcp' ),
			'tools/call:semrush_backlinks_overview' => __( 'Read Semrush backlink overview', 'more-mcp' ),
			'tools/call:semrush_backlinks_list' => __( 'Read Semrush backlinks', 'more-mcp' ),
			'tools/call:semrush_backlink_anchors' => __( 'Read Semrush backlink anchors', 'more-mcp' ),
			'tools/call:semrush_referring_domains' => __( 'Read Semrush referring domains', 'more-mcp' ),
			'tools/call:semrush_url_keywords' => __( 'Read Semrush URL keywords', 'more-mcp' ),
			'tools/call:semrush_api_units' => __( 'Checked Semrush API balance', 'more-mcp' ),
			'tools/call:dataforseo_serp' => __( 'Looked up live search results', 'more-mcp' ),
			'tools/call:dataforseo_keyword_volume' => __( 'Read keyword search volume', 'more-mcp' ),
			'tools/call:dataforseo_ranked_keywords' => __( 'Read ranked keywords', 'more-mcp' ),
			'tools/call:dataforseo_backlinks_summary' => __( 'Read backlink summary', 'more-mcp' ),
			'tools/call:dataforseo_referring_domains' => __( 'Read referring domains', 'more-mcp' ),
			'tools/call:dataforseo_onpage_instant' => __( 'Ran an on-page check', 'more-mcp' ),
			'tools/call:seranking_domain_overview' => __( 'Checked SE Ranking domain overview', 'more-mcp' ),
			'tools/call:seranking_domain_overview_global' => __( 'Checked SE Ranking global overview', 'more-mcp' ),
			'tools/call:seranking_domain_keywords' => __( 'Read SE Ranking domain keywords', 'more-mcp' ),
			'tools/call:seranking_keyword_overview' => __( 'Read SE Ranking keyword data', 'more-mcp' ),
			'tools/call:seranking_keyword_compare' => __( 'Compared SE Ranking keywords', 'more-mcp' ),
			'tools/call:seranking_domain_competitors' => __( 'Read SE Ranking competitors', 'more-mcp' ),
			'tools/call:seranking_backlinks' => __( 'Read SE Ranking backlinks', 'more-mcp' ),
			'tools/call:seranking_domain_authority' => __( 'Read SE Ranking domain authority', 'more-mcp' ),
			'tools/call:seranking_subdomains' => __( 'Read SE Ranking subdomains', 'more-mcp' ),
			'tools/call:seranking_top_pages' => __( 'Read SE Ranking top pages', 'more-mcp' ),
			'tools/call:seranking_longtail_keywords' => __( 'Read SE Ranking long-tail keywords', 'more-mcp' ),
			'tools/call:seranking_related_keywords' => __( 'Read SE Ranking related keywords', 'more-mcp' ),
			'tools/call:seranking_question_keywords' => __( 'Read SE Ranking question keywords', 'more-mcp' ),
			'tools/call:seranking_similar_keywords' => __( 'Read SE Ranking similar keywords', 'more-mcp' ),
			'tools/call:seranking_ai_visibility' => __( 'Checked SE Ranking AI visibility', 'more-mcp' ),
			'tools/call:gsc_list_sites' => __( 'Listed Search Console sites', 'more-mcp' ),
			'tools/call:gsc_search_analytics' => __( 'Read Search Console analytics', 'more-mcp' ),
			'tools/call:gsc_inspect_url' => __( 'Inspected a URL in Search Console', 'more-mcp' ),
			'tools/call:gsc_list_sitemaps' => __( 'Listed Search Console sitemaps', 'more-mcp' ),
			'tools/call:gsc_get_sitemap' => __( 'Read a Search Console sitemap', 'more-mcp' ),
			'tools/call:ga4_list_accounts' => __( 'Listed Analytics accounts', 'more-mcp' ),
			'tools/call:ga4_list_properties' => __( 'Listed Analytics properties', 'more-mcp' ),
			'tools/call:ga4_get_property' => __( 'Read an Analytics property', 'more-mcp' ),
			'tools/call:ga4_list_data_streams' => __( 'Listed Analytics data streams', 'more-mcp' ),
			'tools/call:ga4_run_report' => __( 'Ran an Analytics report', 'more-mcp' ),
			'tools/call:ga4_run_pivot_report' => __( 'Ran an Analytics pivot report', 'more-mcp' ),
			'tools/call:ga4_realtime_report' => __( 'Read Analytics realtime data', 'more-mcp' ),
			'tools/call:ga4_metadata' => __( 'Read Analytics metadata', 'more-mcp' ),
			'tools/call:ga4_list_custom_dimensions' => __( 'Listed Analytics custom dimensions', 'more-mcp' ),
			'tools/call:ga4_list_custom_metrics' => __( 'Listed Analytics custom metrics', 'more-mcp' ),
			'tools/call:ga4_list_conversion_events' => __( 'Listed Analytics conversions', 'more-mcp' ),
		);
	}
}
